### ISSUE TITLE
ListPresenter's menu block should not get a MenuMorph as argument but a MenuPresenter

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#11]
We have presenters for the menu but apparently, they might return directly a Morph after the building.

**Comment by juliendelplanque** [comment]
This issue should be renamed as: "ListPresenter's menu block should not get a MenuMorph as argument but a MenuPresenter" instead.

The problem is that the abstraction layer provided by Spec is broken then since you need to touch Morph.

Here is the snippet allowing to reproduce this issue.
```
ListPresenter new
	items: #(1 2 3);
	menu: [ :menuMorph | menuMorph inspect ];
	openWithSpec
```

Execute this snippet and right click on an item of the list. You'll see what is inspected is a MenuMorph and not a MenuPresenter.

**Comment by jecisc** [comment]
Done.
