### ISSUE TITLE
SpChooserPresenter swallows items after removing them and then adding others

### ISSUE THREAD

**Issue by n1toxyz** [pharo-spec/Spec#1340]
**Bug description**
After opening an instance of SpChooserPresenter and opening it as a window and then removing all or a item(s) from the targetList via a removal button (buttons named '<' or '<<') and then selecting an item in the sourceList and adding it via the button named '>' to the targetList removes/hides all previously removed items from the sourceList and doesn't allow to select or add them anymore.

**To Reproduce**
1. Open an SpChooserPresenter in the playground with e.g. `(SpChooserPresenter sourceItems: #('Apple' 'Pear' 'Melon') chosenItems: #('Peach')) open.`
2. Click on button '<<' or alternatively select 'Peach' and then click on button '<'
3. Now select for example 'Melon' and then click on the button '>'

Now 'Melon' is shown in the targetList but 'Peach' has disappeared from the sourceList is not shown there anymore, thus preventing selecting and adding it again if desired.

**Expected behavior**
After removing an item or multiple items from the targetList via a button and then adding other items to targetList, the previously removed items should stay selectable and addable in the sourceList.

**Screenshots**
Opened SpChooserPresenter:
![chooser_before](https://user-images.githubusercontent.com/29785597/209002923-3c936c21-40d1-4e1e-9436-26a328121570.png)

After moving all or one item to sourceList and selecting a new item for moving to targetList:
![chooser_between](https://user-images.githubusercontent.com/29785597/209002965-6923b38f-d32f-47df-80c9-ec23c07a56d5.png)

After moving previously selected item to targetItems list:
![chooser_after](https://user-images.githubusercontent.com/29785597/209002998-df933a99-14d1-4695-a9d2-bfecb4efade7.png)

Peach has disappeared from sourceList.

**Version information:**
 - OS: Slackware 15.0 64bit
 - Pharo 11 latest

**Expected development cost**
I don't know yet, but I think it must be something in the methods `#removeAll` or `#removeSelected`.  At first glance both look fine to me, but somehow the items disappear. I haven't investigated much yet as I hadn't time.

**Additional context**
None so far

**Comment by Ducasse** [comment]
I confirm that I can reproduce the problem in latest Pharo 11.

**Comment by Ducasse** [comment]
@estebanlm this is important that we fix it because I moved users of duplicated widgets to this one.

**Comment by demarey** [comment]
Here is a test case for this issue:
```smalltalk
testMovingItemsFromTargetToSourceThenMovingOtherItemFromSourceToTargetKeepsAllNotTargetedItemsInSource

	| allItems targetedItem |
	allItems := #('Apple' 'Pear' 'Melon' 'Peach').
	targetedItem := 'Peach'.
	presenter := SpChooserPresenter sourceItems: (allItems copyWithout: targetedItem) chosenItems: { targetedItem }.	
	presenter targetList selectItem: targetedItem.
	presenter removeSelected.
	presenter sourceList selectItem: 'Melon'.

	self assert: (presenter sourceList items includes: targetedItem).
	presenter addSelected.	
	self assert: (presenter sourceList items includes: targetedItem).
```

It fails because chosenItems are not part of sourceItems.
We could enforce this by merging chosenItems and sourceItems to get the whole list of items, taking care of removing duplicates but it looks overkill.
Maybe we should just enforce that chosenItems are part of sourceItems.
@Ducasse @estebanlm What do you think ?

**Comment by Ducasse** [comment]
Thanks a lot for the test!!!

**Comment by Ducasse** [comment]
Removing duplicates can be difficult. 
I think that chosenItems should be part of sourceitems (but I'm not concentrated enought to get a real anwser).

**Comment by uNouss** [comment]
I tested it in pharo12 and it still has the same problem.

**Comment by estebanlm** [comment]
thanks for report, I will check it as soon as possible (traveling for a conf now, so it will probably be later this month ;)

**Comment by sanjayminni** [comment]
I am hit by this or an allied bug in WorldMenu->Browse->Finder->[Packages...] Package Chooser reported in 
https://github.com/pharo-project/pharo/issues/13907

On first time popup if we apply a filter in available items panel and move the filtered items then after the move the remaining items are not displayed in the available items panel.  If this is the same issue then I propose a different expected behaviour than as suggested by  @n1toxyz above.

after the move the source / available items should be refreshed with the remaining items and that should suffice. 
Currently this behaviour is actually happening but on the second time onwards, it is not happening on first time popup. To see click  Finder->[Packages...] for a second time. 

since its behaving as acceptable on second time, its hopeful the bug may be somewhat easier to track / close
![243407978-b05a65e0-f149-4608-a525-a187700026d7](https://github.com/pharo-spec/Spec/assets/12030766/1a2dffe9-a41f-48aa-a15d-064ae386956a)
