### ISSUE TITLE
would it make sense to have inform: and alert:

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1416]
In morphic or even spec code people use self inform: or alert: because it is defined on Object. 
Would it make sense to propose an alternate implementation of such methods in SpPresenter that opens a configured SpDialog.
Like that we can get rid of the self uiManager inform:

I can do a PR but only if it makes sense so let me know.

**Comment by estebanlm** [comment]
in fact we had that but we removed it because is not a good API (that ends in a profusion of methods for each minimal variant).
what you have now (we can always improve the api and enhance it) is the equivallent of what we had there in application, as builders e. g. :

```Smalltalk
self application newInform
title: 'A 'window title';
label: 'a label';
acceptLabel: 'Yes, do it';
openModal
```

and you have also newRequest, newRequestText, newConfirm and newSelect.
this is a lot more maleable, IMO.

**Comment by Ducasse** [comment]
Ok I started to convert all the call from within Syc*Presenter to uiManager to an internal self inform: method. 
And I was thinking that I could define it following the pseudo code below (no idea if there is a NullApplication.  

```
inform: astring
    self application 
     ifNil:[ self localInform: astring
    ifNotNil: [:a | a inform: astring ]

```

But I will use the self application newInform
I will remove the uiManager call in Syc and in the copy I'm working on for the refactoring driver.
