### ISSUE TITLE
Introduce ToolPresenter

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#255]
A toolPresenter subclass of ApplicationPresenter should support a toolsuite abstraction: registration mechanism for accessing other tools from the suite via names (like Smalltalk tools but not using a global variable). 

A second generation could add a notification to update the mapping when on of the toolsuite changes.

**Comment by Ducasse** [comment]
We have to check because we have AbstractTool as a subclass a Model.

**Comment by Ducasse** [comment]
We should also UIManager default so we should really think about removing the direct global access.

**Comment by estebanlm** [comment]
Honestly I think `ToolPresenter` should be called `PharoApplication`  or `PharoApplicationPresenter`.
I still don't know why an `SpecApplication` should be a presenter itself (Since it will be the starting point of any application). 

So far, according which how I'm thinking this: 
- There is an Application who is the starting point of... well, any application.
- all ComposablePresenter knows which application they belong.

then, applications responsibility is to handle the application context: 
- the windows contained in application.
- the resources for that application (icons, theme, etc)
- ?

**Comment by CafeKrem** [comment]
There is another issue about replacing UIManager. I tag it.  
https://github.com/pharo-spec/Spec/issues/502

**Comment by estebanlm** [comment]
there is already `StPharoApplication` in NewTools-Core package. 
I think this is the `ToolPresenter` requested? (and I think it belongs to NewTools, not to Spec2)
