### ISSUE TITLE
The FastTablePresenter is missing updateList method

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#265]
The ListPresenter contains the method #updateList. The FastTablePresenter is missing the alternative of it. It should be implemented for the API compatibility

**Comment by pavel-krivanek** [comment]
it is needed for example as soon as you add a new item into the list dynamically.

**Comment by pavel-krivanek** [comment]
[Issue265.zip](https://github.com/pharo-spec/Spec/files/2875005/Issue265.zip)

An example. You may change the `Issue265>>#initializeWidgets` to see how it works for the standard lists

**Comment by estebanlm** [comment]
`FastTablePresenter` should not be used since it's replaced with `TablePresenter`.
Please use that one, I'm sure you will find lots of things that are not there.
As a side note, while you may ask to apis to be similar for similar components (as a list and a table), not always what is present in one will be in the other ;)
