### ISSUE TITLE
Simplify update hack

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#337]
We have an "update hack" in the baseline that will make problems every time we want to synchronize with Pharo.

We should find a solution that makes it more straight forward

**Comment by guillep** [comment]
See comments in https://github.com/pharo-project/pharo/pull/2735

**Comment by guillep** [comment]
- Cleanup warnAboutLosingChangesForSpec: extension

**Comment by jecisc** [comment]
So the concrete problem:

Some changes we did, and might do in the future in Spec, can cause some packages to become dirty in the middle of an update.

Example:
- We have Spec-Core that contained SpecLayout in Pharo 7. It also depends on the Spec-Layout package.
- In the updated version of Spec, the class SpecLayout was moved to Spec-Layout.
- During an update of Spec in Pharo first step of Metacello was to load Spec-Layout package. This implied that the class SpecLayout vanished from Spec-Core and the package was marked as dirty.
- Then the package Spec-Core was loaded. The Monticello model then stopped the loading and asked the user "You will discard changes to a dirty package. Merge/Load/Cancel". 

This dialog cannot be disabled and it's really a bother to provide a default answer because it cannot be done in the baseline. You need an #on:do: on all loading instructions of projects depending on Spec. 

So my current solution is to use a metalink to remove this warning when we load in headless.
