### ISSUE TITLE
GridLayout is not able to rebuild itself

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#391]
When you need to on the fly to replace one presenter with another one, you need to do:
```
	self needRebuild: false.
	self buildWithSpec.
```
However, this code does not work as soon as you use the SpecGridLayout (and maybe others too). See the attached code

[TstPresenter.zip](https://github.com/pharo-spec/Spec/files/2945982/TstPresenter.zip)

**Comment by pavel-krivanek** [comment]
moreover, the next problems come when the embedded presenter uses some new layout

**Comment by jecisc** [comment]
I opened a duplicated issue that I closed seen this one. Here is what I wrote on the other one:
------------------------

I tried to migrate the layout of SpecDemo class to use the new layouts. 

I used this layout:

```Smalltalk
defaultSpec
	^ SpecBoxLayout newVertical
		add: #menu withConstraints: [ :constraints | constraints height: self toolbarHeight ];
		add:
			(SpecBoxLayout newHorizontal
				position: (StandardFonts defaultFont widthOfString: 'M') * 20;
				add: #list;
				add: #page;
				yourself);
			yourself
```

WIth this layout the demo is broken because when we select an item in the list it will not update the demo.

My guess is that the problem comes from UI rebuild because SpecDemo is dynamicaly changing components using this code:

```Smalltalk
list
	whenSelectionChangedDo: [ :selection | 
		selection selectedItem
			ifNotNil: [ :newPageClass | 
				newPageClass = self selectedPage
					ifFalse: [ self selectedPage: newPageClass.
						page := self instantiate: newPageClass.
						self needRebuild: false.
						self buildWithSpec.
						list selectItem: self selectedPage ] ]
			ifNil: [ "Avoid the user to have no page selected at all." list setSelectedItem: self selectedPage ] ]
```

This technic is valid in Spec and described in the Spec book. I guess the new executable layouts does not manage this case.
