### ISSUE TITLE
Adapters bindings default fonts methods are not used

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#53]
All subclasses of the abstract spec bindings have a method #defaultFont 

IMO it's not the responsibility of the adapter bindings to know the font.

Anyone thinking like that?

**Comment by pavel-krivanek** [comment]
This part needs a redesign. I had to introduce a `StubFixedFont` because of it to be able to have Morphic independent Spec. 
Spec probably needs some limited representation of fonts (see AbstractFont?) but just name, size and style should be enough. I think that currently, it needs it for some measurements with layouts. That needs to be adapters responsibility.
