### ISSUE TITLE
Why self title: self title does not change the window title?

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#546]
In ChangeSorterPresenter I have to do 

	self window title: self title.

**Comment by jecisc** [comment]
@Ducasse We are changing the way windows properties are managed because they should not be stored in all ComposablePresenter but only in the WindowPresenter. 

Julien and Clément reported this issue IIRC and I know how to fix it. I just did not had the time :) 
The fix is to remove the titleHolder variable from ComposablePresenter (Yes :D) and to replace #title: by:

```Smalltalk
title: aString
    "Update the title of the window. In case this method is call before the opening of the window, it will do nothing because the window does not exist yet. To set an initial title, override the method #initializeWindow:"

    self withWindowDo: [ :window | window title: aString ]
```

**Comment by Ducasse** [comment]
Ok now storing is different than declaring a property. 
This is a comment for the issue about changersorter but related
so the user could still write initialExtent ^ 300@300 and the windowPresenter stores it. 
As it is done like now.

**Comment by jecisc** [comment]
Fixed in: https://github.com/pharo-spec/Spec/pull/563
