### ISSUE TITLE
Add an #autoScale: to the ImagePresenter

### ISSUE THREAD

**Issue by 570gina** [pharo-spec/Spec#608]
Can we add an #autoScale: to the ImagePresenter?
I want to access the autoScale value from the outside.

**Comment by jecisc** [comment]
Hi Gina,

It is already in SpImagePresenter, but I think I might know why you did not find it.

We took the decision to make Spec 1 and Spec 2 be able to cohabitate. In order to make this happen, we just renamed all classes of Spec so that they start with `Sp`. So, if you use this new version of Spec you will have the #autoScale: method.

In order to migrate, you should inherit from SpPresenter instead of ComposablePresenter. Also, all classes from Spec 2 are now prefixed with `Sp` and all references should be updated. 

The planing with Spec is like this:
- Currently, we have an updated Spec 1 (I'll call it Spec 1.5) in Pharo 8.
- Soon, we will integrate this new version of Spec, and we will have Spec 1.5 and Spec 2 in the Pharo 8 image. 
- We will wait some weeks so that everyone can migrate their applications from Spec 1.5 to Spec 2 and then we will revert all changes to Spec 1.5 in order to get back the version of Spec that was in Pharo 7, Spec 1.
