### ISSUE TITLE
Table in spec2 not filtering

### ISSUE THREAD

**Issue by gbosetti** [pharo-spec/Spec#871]
If you instantiate a table:

> self newTable
> 		addColumn: (SpStringTableColumn title: 'Name' evaluated: #name);
> 			items: classes;
> 		itemFilter: [ :each :pattern | 
> 			each crTrace.
> 			each asLowercase includesSubstring: pattern asLowercase.
> 	];

The user can not filter when typing. To fix it I introduced the following changes:
```

FTSimpleDataSource > newDataSourceMatching: aFTFilter
	| newElements elems newDataSource modelCopy|
	elems := self model items.
	
	newElements := elems class withAll: (elems select: [ :each | 
		aFTFilter matches: (self toString: each) ]).
	
	newDataSource := self copy.
	modelCopy := self model copy.
	modelCopy prepareForFilteredDataSourceWith: newElements.
	newDataSource model: modelCopy.
	
	^ newDataSource "self class new elements: newElements"


SpTablePresenter > prepareForFilteredDataSourceWith: items
	model collection: items

```

**Comment by estebanlm** [comment]
Hi, 

Here is the thing: I do not think filtering should be present as a low-level api in the list/table/tree presenters. Filtering is a high level order feature and my intention was to remove that functionality and instead replace it by a component, something at the style of `SpEditableListPresenter`.

I do not find useful to add the filtering to `SpListPresenter` because in that case we need to implement it in the adapter level and ultimately in the backend. This posses several problems (for example in morphic, making the filter work will disable the search function).

Why would we do this while we already have the high-level abstractions that would allow us to create the presenter in a better/more maintainable way?

In that sense, I was expecting to use @juliendelplanque work instead. I don't know what is the actual status, but this would be my take on this.

**Comment by estebanlm** [comment]
fixed in https://github.com/pharo-spec/Spec/releases/tag/v0.7.5
