### ISSUE TITLE
SpTablePresenter should accept ButtonColumn

### ISSUE THREAD

**Issue by mahugnon** [pharo-spec/Spec#891]
I want to represent color in my SpTable presenter.  I think buttonColumns combine with composite column will do the job for me. But so far SpTable presenter accepts only checkboxColumn.  
 Here is my proposition: 
```Smalltalk
SpTableColumn subclass: #SpButtonTableColumn
	instanceVariableNames: 'action label color'
	classVariableNames: ''
	package: 'Spec2-Core-Widgets-Table'

SpButtonTableColumn>> acceptColumnVisitor: aBuilder
	^ aBuilder visitButtonColumn: self

SpMorphicTableColumnVisitor>> visitButtonColumn: aTableColumn
	| presenter |
	presenter := SpButtonPresenter new.
	aTableColumn color
		ifNotNil: [ :valuable | presenter color: (valuable cull: self item) ].
	aTableColumn label
		ifNotNil: [ :valuable | presenter label: (valuable cull: self item) ].
	aTableColumn action
		ifNotNil: [ :valuable | presenter action: [ valuable cull: self item ] ].
	self addCellMorph: presenter buildWithSpec column: aTableColumn
```

**Comment by estebanlm** [comment]
This is not going to be possible in Spec2 for the moment, since this is not portable between backends (Gtk does not supports them, and I do not have the time to hack a solution, which will take a lot of effort). 
You have other options here: 
- you can use an action bar or a toolbar for your button options (enabling/disabling what corresponds)... which is basically what most GUI recommend anyway.
- you can use a SpComponentListPresenter (but you lose a lot of other things there like headers and that).
